version: 2
jobs:
  test:
    docker:
      - image: circleci/node:16.6.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          - v2-dependencies-

      - run: npm install

      - save_cache:
          paths:
          - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: validate renovate config
          command: |
            npx --package renovate -c 'renovate-config-validator'

      - run:
          name: test
          command: |
            npm run test:ci

      - run:
          name: lint
          command: npm run lint

      - run:
          name: build
          command: npm run build

workflows:
  version: 2
  build-workflow:
    jobs:
    - test
