name: Check code quality

on:
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '!README.md'
      - '!.gitignore'
      - '!LICENSE.txt'
  workflow_call:

jobs:
  check-code-quality:
    timeout-minutes: 20
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.node-version'
          cache: npm

      - run: |
          node --version
          npm --version

      - name: npm install
        run: npm ci --no-audit --no-fund

      - name: build
        run: npm run build

      - name: lint
        run: npm run lint

      - name: test
        run: |
          npm run test:ci
