name: Deploy to GAE

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!README.md'

jobs:
  check-before-deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: npm install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test:ci

      - name: build
        run: npm run build

  deploy:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs:
      - check-before-deploy

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: npm install
        run: npm ci

      - name: build app.yaml
        run: npm run generate:appYaml
        env:
          NODE_ENV: production
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_APP_LEVEL_TOKEN: ${{ secrets.SLACK_APP_LEVEL_TOKEN }}
          REMO_API_TOKEN: ${{ secrets.REMO_API_TOKEN }}
          STORAGE_TYPE: ${{ secrets.STORAGE_TYPE }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v4'
        with:
          workload_identity_provider: 'projects/166962166615/locations/global/workloadIdentityPools/github-sota1235-bot-deploy/*'
          service_account: 'sota1235-bot-gae-deploy@sandbox-4affa.iam.gserviceaccount.com'

      - id: deploy
        uses: 'google-github-actions/deploy-appengine@v0'

      - id: debug
        run: 'curl "${{ steps.deploy.outputs.url }}"'

      - name: Slack Notification
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ACTIONS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          text: "sota1235 Botがデプロイされました"
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Commit hash",
                    "value": "${{ github.sha }}",
                    "short": true
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ env.ACTIONS_URL }}"
                  }
                ]
              }
            ]
